name: CI backend

on:
  push:
    paths:
      - 'backend/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run npm ci
        run: npm ci
        working-directory: backend
      - name: Run test case
        run: npm run test
        working-directory: backend
