name: CI Frontend

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run npm ci
        run: npm ci
        working-directory: frontend
      - name: Run test case
        run: npm run test:unit
        working-directory: frontend
